version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "19:54"
  groups:
    python-packages:
      patterns:
        - "*"
  target-branch: "dev"
  labels:
    - "dependecies"