version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "18:01"
  groups:
    python-packages:
      patterns:
        - "*"
  target-branch: "main"
  labels:
    - "dependecies"