version: '3'
services:
   redis: 
     image: redis
   flask:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
        env_file:
            - .env
